"""initial schema

Revision ID: 4b6e78bf0665
Revises: 
Create Date: 2026-06-29 17:42:42.433228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6e78bf0665'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_scores',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('authenticity_score', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('impact_reason', sa.Text(), nullable=True),
    sa.Column('authenticity_reason', sa.Text(), nullable=True),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('failed_articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('publication', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filtered_articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('publication', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('publication', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Text(), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('dropped_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seen_articles',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('seen_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seen_articles')
    op.drop_table('runs')
    op.drop_table('run_articles')
    op.drop_table('filtered_articles')
    op.drop_table('failed_articles')
    op.drop_table('article_scores')
    # ### end Alembic commands ###
