"""add subscribers and newsletter_deliveries

Revision ID: 5c6a06c70a64
Revises: ebfc671a4078
Create Date: 2026-07-01 21:03:26.172935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6a06c70a64'
down_revision: Union[str, Sequence[str], None] = 'ebfc671a4078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'email', name='uq_delivery_run_email')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('confirm_token', sa.Text(), nullable=True),
    sa.Column('unsubscribe_token', sa.Text(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirm_token'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    # ### end Alembic commands ###

    # Enable RLS (no policies) — matches the rest of the schema. Only the
    # service_role (portfolio) and the table-owning role (this app) reach these;
    # the public anon/publishable key cannot read subscriber PII.
    op.execute("ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE public.newsletter_deliveries ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    op.drop_table('newsletter_deliveries')
    # ### end Alembic commands ###
