"""SQLAlchemy ORM models — the persistence schema for the news pipeline.

These models replace the hand-written ``CREATE TABLE`` statements that used to
live in ``db.py``. Alembic owns schema changes (autogenerated by diffing this
metadata against the live database); do not hand-edit table DDL elsewhere.

Timestamp typing follows existing app semantics:

* ``runs.started_at`` / ``runs.completed_at`` / ``seen_articles.seen_at`` are
  application-managed ISO-8601 strings (the dashboard slices them as text and
  orders by them lexicographically), so they stay ``Text``.
* ``failed_articles.failed_at`` / ``article_scores.cached_at`` are
  database-defaulted audit columns, so they become ``timestamptz`` with a
  ``now()`` server default.
"""

from __future__ import annotations

from sqlalchemy import BigInteger, DateTime, Float, Integer, Text, UniqueConstraint, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Declarative base holding the shared MetaData (used by Alembic)."""


class SeenArticle(Base):
    __tablename__ = "seen_articles"

    url: Mapped[str] = mapped_column(Text, primary_key=True)
    # App-managed ISO-8601 string (main.py supplies it explicitly per run).
    seen_at: Mapped[str | None] = mapped_column(Text)


class Run(Base):
    __tablename__ = "runs"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    started_at: Mapped[str | None] = mapped_column(Text)
    completed_at: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str | None] = mapped_column(Text)
    article_count: Mapped[int | None] = mapped_column(Integer)
    html: Mapped[str | None] = mapped_column(Text)
    error: Mapped[str | None] = mapped_column(Text)
    dropped_count: Mapped[int | None] = mapped_column(Integer, server_default="0")
    failed_count: Mapped[int | None] = mapped_column(Integer, server_default="0")


class RunArticle(Base):
    __tablename__ = "run_articles"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text)
    url: Mapped[str | None] = mapped_column(Text)
    publication: Mapped[str | None] = mapped_column(Text)
    published_at: Mapped[str | None] = mapped_column(Text)
    rank_score: Mapped[float | None] = mapped_column(Float)


class FailedArticle(Base):
    __tablename__ = "failed_articles"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(Text, nullable=False)
    url: Mapped[str | None] = mapped_column(Text)
    title: Mapped[str | None] = mapped_column(Text)
    publication: Mapped[str | None] = mapped_column(Text)
    reason: Mapped[str | None] = mapped_column(Text)
    failed_at: Mapped[object] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class FilteredArticle(Base):
    __tablename__ = "filtered_articles"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(Text, nullable=False)
    url: Mapped[str | None] = mapped_column(Text)
    title: Mapped[str | None] = mapped_column(Text)
    publication: Mapped[str | None] = mapped_column(Text)
    relevance_score: Mapped[int | None] = mapped_column(Integer)
    relevance_reason: Mapped[str | None] = mapped_column(Text)


class ArticleScore(Base):
    __tablename__ = "article_scores"

    url: Mapped[str] = mapped_column(Text, primary_key=True)
    impact_score: Mapped[int | None] = mapped_column(Integer)
    authenticity_score: Mapped[int | None] = mapped_column(Integer)
    relevance_score: Mapped[int | None] = mapped_column(Integer)
    impact_reason: Mapped[str | None] = mapped_column(Text)
    authenticity_reason: Mapped[str | None] = mapped_column(Text)
    relevance_reason: Mapped[str | None] = mapped_column(Text)
    # Short hash of the triage / scoring system prompt in effect when this row
    # was written. A cache read only reuses a value when its stage's hash still
    # matches the current code, so a rubric change auto-invalidates stale rows.
    triage_version: Mapped[str | None] = mapped_column(Text)
    score_version: Mapped[str | None] = mapped_column(Text)
    cached_at: Mapped[object] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Subscriber(Base):
    __tablename__ = "subscribers"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    email: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="pending")
    # Tokens are generated by the portfolio; this service only reads unsubscribe_token.
    confirm_token: Mapped[str | None] = mapped_column(Text, unique=True)
    unsubscribe_token: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    subscribed_at: Mapped[object] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    confirmed_at: Mapped[object | None] = mapped_column(DateTime(timezone=True))
    unsubscribed_at: Mapped[object | None] = mapped_column(DateTime(timezone=True))


class NewsletterDelivery(Base):
    """One row per (run, subscriber): whether that issue was sent or failed."""

    __tablename__ = "newsletter_deliveries"
    __table_args__ = (UniqueConstraint("run_id", "email", name="uq_delivery_run_email"),)

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(Text, nullable=False)
    email: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False)  # "sent" | "failed"
    error: Mapped[str | None] = mapped_column(Text)
    sent_at: Mapped[object] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
